### ISSUE TITLE
how to use DNAnexus Workflow to assembly genome

### ISSUE THREAD

**Issue by zhoudreames** [VGP/vgp-assembly#45]
I want to use your fArcCen1 Assembly Tutorial for training,but  I dont know find your subject in DNAnexus websites.thank you !

**Comment by zhoudreames** [comment]
@Arkarachai

**Comment by Arkarachai** [comment]
Are you associated with VGP? If not, can you contact support@dnanexus.com? These pipelines are on DNAnexus which is a paid service. We can grant you access via your organization. You could mention my name Chai when you submit the ticket.
Otherwise, Arang and the team also maintain the script to run these tools locally here https://github.com/VGP/vgp-assembly/tree/master/pipeline.

**Comment by Arkarachai** [comment]
If you are part of VGP, contact Giulio, Olivier, or Arang, they could grant you access to it.

**Comment by zhoudreames** [comment]
> If you are part of VGP, contact Giulio, Olivier, or Arang, they could grant you access to it.

thank you!
