### ISSUE TITLE
Sex chromosome assembly

### ISSUE THREAD

**Issue by zhoudreames** [VGP/vgp-assembly#46]
in your article ,only briefly to introduce the method about Sex chromosome assembly，if you can provide more detail information or  flow about the Sex chromosome assembly. thank you for your help!

**Comment by zhoudreames** [comment]
@skoren @Arkarachai @godotgildor

**Comment by arangrhie** [comment]
Hi @zhoudreames,

Most of the sex chromosomes were assembled and scaffolded through the standard whole genome assembly pipeline procedure (VGP standard pipeline v1.0~1.6) or the trio binning procedure (trio pipeline v1.0~v1.6). Sex chromosome assignment happens over the manual curation process.

As described in the paper, the trio version of the zebra finch assembled both sex chromosomes independently except for the PAR regions, or regions where haplotype specific reads are difficult to bin, because homologous haplotypes were nearly identical or both haplotypes were shared among the parental genomes (no marker found for binning).

In the final curation step, the sex chromosomes were curated together with the autosomes. We found a few additional smaller contigs/scaffolds belong to a particular sex chromosome from sex-chromosome specific genes and mapping coverage evidence.

Most recently, we found HiFi reads were better in resolving highly repetitive regions than CLR reads, including part of sex chromosomes. Still, finding and assigning pieces to the correct chromosome is a challenge. We find the value of using orthogonal datasets (linkage, BACs, genes, closest species' reference, etc.). If possible, find a trio with the most diverged parental (ancestral) genomes.

All the best with your sex chromosome assembly!
-Arang

**Comment by zhoudreames** [comment]
> Hi @zhoudreames,
> 
> Most of the sex chromosomes were assembled and scaffolded through the standard whole genome assembly pipeline procedure (VGP standard pipeline v1.0 ~ 1.6) or the trio binning procedure (trio pipeline v1.0 ~ v1.6). Sex chromosome assignment happens over the manual curation process.
> 
> As described in the paper, the trio version of the zebra finch assembled both sex chromosomes independently except for the PAR regions, or regions where haplotype specific reads are difficult to bin, because homologous haplotypes were nearly identical or both haplotypes were shared among the parental genomes (no marker found for binning).
> 
> In the final curation step, the sex chromosomes were curated together with the autosomes. We found a few additional smaller contigs/scaffolds belong to a particular sex chromosome from sex-chromosome specific genes and mapping coverage evidence.
> 
> Most recently, we found HiFi reads were better in resolving highly repetitive regions than CLR reads, including part of sex chromosomes. Still, finding and assigning pieces to the correct chromosome is a challenge. We find the value of using orthogonal datasets (linkage, BACs, genes, closest species' reference, etc.). If possible, find a trio with the most diverged parental (ancestral) genomes.
> 
> All the best with your sex chromosome assembly!
> -Arang

thank you!
